### ISSUE TITLE
Only the /dist folder to Heroku

### ISSUE THREAD

**Issue by mihailtd** [unchained/gitlab-heroku-ci#1]
Hello,
Can you please tell me how do you only send the dist folder to Heroku instead of the whole project?
Thanks!

**Comment by davidkregl** [comment]
Hey Mihas,

We do not use Heroku anymore we moved our whole server infrastructure to DigitalOcean. But I suppose you build your application and using the command in .gitlab-cy.yml delete everything except the dist folder and the you can save it as artifqcts and deploy it wherever you want.

David Kregl
backend vývojář
+420 733 330 705
david@unchained.studio
unchained.studio

**Comment by mihailtd** [comment]
Giving it a try, Thanks!
